# Generated by Django 3.2.3 on 2024-07-19 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='document',
        ),
        migrations.RemoveField(
            model_name='note',
            name='image',
        ),
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='notes/images/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='notes.note')),
            ],
        ),
        migrations.CreateModel(
            name='NoteDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='notes/documents/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='notes.note')),
            ],
        ),
    ]
