# Generated by Django 3.2.3 on 2024-07-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20240719_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='drawing',
            field=models.TextField(blank=True, null=True),
        ),
    ]
