# Generated by Django 5.0.4 on 2024-09-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resources/pdf/'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
