# Generated by Django 5.0.4 on 2024-10-04 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_study_methods',
        ),
        migrations.RemoveField(
            model_name='user',
            name='year',
        ),
        migrations.AddField(
            model_name='user',
            name='connections',
            field=models.ManyToManyField(blank=True, related_name='connected_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='is_senior',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
