# Generated by Django 5.2.17 on 2026-09-12 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_user_availability_remove_user_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='connections',
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
