# Generated by Django 5.0.6 on 2024-07-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='selfstudy',
            name='name',
        ),
        migrations.AddField(
            model_name='assignment',
            name='chapname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='subname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='selfstudy',
            name='chapname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='selfstudy',
            name='subname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
