[supervisord]
nodaemon=true

[program:gunicorn]
command=gunicorn studybuddy.wsgi:application --bind 0.0.0.0:8000 --workers=4
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:celery]
command=celery -A studybuddy worker --loglevel=info
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:celery-beat]
command=celery -A studybuddy beat --loglevel=info
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr 