# Generated by Django 3.2.3 on 2024-07-18 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testseries', '0003_auto_20240719_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
